# Generated by Django 4.0.3 on 2022-04-11 17:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название')),
                ('company_inn', models.CharField(max_length=200, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_date', models.DateField(verbose_name='Дата отправки в брак')),
                ('defect_shift', models.CharField(choices=[('1', 'Первая смена'), ('2', 'Вторая смена')], max_length=30, verbose_name='Смена')),
                ('defect_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('defect_unit', models.CharField(choices=[('шт', 'шт'), ('кг', 'кг')], max_length=20, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Брак',
                'verbose_name_plural': 'Браки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('product_number', models.CharField(max_length=200, verbose_name='Чертежный номер')),
                ('product_count', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество на складе')),
                ('product_unit', models.CharField(choices=[('шт', 'шт'), ('кг', 'кг')], max_length=20, verbose_name='Единица измерения')),
                ('product_consumption', models.FloatField(verbose_name='Расход на 1 ЖМТ')),
                ('product_type', models.CharField(choices=[('Камаз', 'Камаз'), ('Ярославль', 'Ярославль')], max_length=20, verbose_name='Вид теплообменника')),
                ('product_price', models.IntegerField(blank=True, null=True, verbose_name='Цена без НДС')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
            },
        ),
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trash_date', models.DateField(verbose_name='Дата отправки в брак')),
                ('trash_shift', models.CharField(choices=[('1', 'Первая смена'), ('2', 'Вторая смена')], max_length=30, verbose_name='Смена')),
                ('trash_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('trash_unit', models.CharField(choices=[('шт', 'шт'), ('кг', 'кг')], max_length=20, verbose_name='Единица измерения')),
                ('trash_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.defect', verbose_name='Наименование изделия')),
            ],
            options={
                'verbose_name': 'Списание',
                'verbose_name_plural': 'Списания',
            },
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateField(verbose_name='Дата прихода')),
                ('import_shift', models.CharField(choices=[('1', 'Первая смена'), ('2', 'Вторая смена')], max_length=30, verbose_name='Смена')),
                ('import_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('import_unit', models.CharField(choices=[('шт', 'шт'), ('кг', 'кг')], max_length=20, verbose_name='Единица измерения')),
                ('import_document', models.CharField(max_length=300, verbose_name='Документ прихода')),
                ('import_price', models.IntegerField(verbose_name='Цена покупки')),
                ('import_from', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.company', verbose_name='От кого')),
                ('import_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.product', verbose_name='Наименование изделия')),
            ],
            options={
                'verbose_name': 'Приход',
                'verbose_name_plural': 'Приходы',
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_date', models.DateField(verbose_name='Дата ухода')),
                ('export_shift', models.CharField(choices=[('1', 'Первая смена'), ('2', 'Вторая смена')], max_length=30, verbose_name='Смена')),
                ('export_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('export_unit', models.CharField(choices=[('шт', 'шт'), ('кг', 'кг')], max_length=20, verbose_name='Единица измерения')),
                ('export_document', models.CharField(max_length=300, verbose_name='Документ ухода')),
                ('export_duration', models.IntegerField(verbose_name='Отсрочка платежа (дней)')),
                ('export_receive_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Дата посутпления платежа')),
                ('export_price', models.IntegerField(verbose_name='Цена продажи')),
                ('export_from', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.company', verbose_name='Кому')),
                ('export_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.product', verbose_name='Наименование изделия')),
            ],
            options={
                'verbose_name': 'Уход',
                'verbose_name_plural': 'Уходы',
            },
        ),
        migrations.AddField(
            model_name='defect',
            name='defect_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.product', verbose_name='Наименование изделия'),
        ),
    ]
