# Generated by Django 4.0.3 on 2022-04-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_defect_defect_count_alter_export_export_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
    ]
