# Generated by Django 4.0.3 on 2022-04-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_defect_options_alter_export_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_reserves',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='На сколько ЖМТ хватит'),
        ),
    ]
