# Generated by Django 4.0.3 on 2022-04-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_product_reserves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_reserves',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='На сколько ЖМТ хватит'),
        ),
        migrations.CreateModel(
            name='HeatExchanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heatExchanger_name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('heatExchanger_number', models.CharField(max_length=200, verbose_name='Чертежный номер')),
                ('heatExchanger_product', models.ManyToManyField(to='inventory.product', verbose_name='Изделия')),
            ],
            options={
                'verbose_name': 'Теплобменник',
                'verbose_name_plural': 'Теплобменники',
            },
        ),
    ]
