# Generated by Django 4.0.3 on 2022-04-25 09:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_product_reserves_heatexchanger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heatexchanger',
            name='heatExchanger_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_export_only',
        ),
        migrations.AddField(
            model_name='heatexchanger',
            name='heatExchanger_count',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество на складе'),
        ),
        migrations.AddField(
            model_name='import',
            name='import_name_heat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.heatexchanger', verbose_name='Наименование теплообменника'),
        ),
        migrations.AlterField(
            model_name='import',
            name='import_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.product', verbose_name='Наименование изделия'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ManyToManyField(to='inventory.heatexchanger', verbose_name='Теплообменники'),
        ),
    ]
