# Generated by Django 4.0.3 on 2022-04-25 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_heatexchanger_heatexchanger_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='export_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.heatexchanger', verbose_name='Наименование изделия'),
        ),
    ]
