# Generated by Django 4.0.3 on 2022-04-25 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_export_export_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='defect_name_heat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.heatexchanger', verbose_name='Наименование теплообменника'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='defect_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.product', verbose_name='Наименование изделия'),
        ),
    ]
